config/routes.rb
Rails.application.routes.draw do
  get 'booking_confirmation/show'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users
  root to: 'pages#home'
  get '/tagged', to: "recipes#tagged", as: :tagged
  get 'chef_dashboard', to: 'dashboards#chef_dashboard', as: :chef_dashboard
  get 'user_dashboard', to: 'dashboards#user_dashboard', as: :user_dashboard

  # /bookings -- /bookings/:id -- /bookings/:id/edit
  resources :bookings, only: [ :index, :show, :destroy, :edit, :update] do
    # /bookings/:id/chef_reviews/new
    resources :chef_reviews, only: [:new, :create]
    # /bookings/:id/recipe_reviews/new
    resources :recipe_reviews, only: [:new, :create]
  end

 # All CRUD actions for recipes
  resources :recipes do
    member do 
      post 'toggle_favorite', to: "recipes#toggle_favorite"
    end
    collection do
      get :top
    end
    # /recipes/:id/bookings/new
    resources :bookings, only: [:new, :create]

    # recipes/:id/measurements/:id
    resources :measurements, only: [:new, :create]
  end

  # /chats  -- /chats/:id
  resources :chats, only: [:index, :show] do
    # chats/:id/messages
    resources :messages, only: [:create, :destroy]
  end

  # /chefs/:id -- /chefs/new  -- /chefs
  resources :chefs, only: [:show, :new, :create, :index, :destroy]
  resources :measurements, only: [:destroy]

  # checkout
  resources :bookings, only: [] do
    resources :checkout_sessions, only: [:new]
    resources :booking_confirmations, only: [:new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  has_one :chat
  has_one :chef_review, dependent: :destroy
  has_one :recipe_review, dependent: :destroy

  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_after_start_time

  private

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, "must be after the start time")
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :booking
  has_many :messages
end

app/models/chef.rb
class Chef < ApplicationRecord
  belongs_to :user
  has_many :recipes, dependent: :destroy
  has_many :bookings, through: :recipes
  has_many :chef_reviews, through: :bookings

  validates :cuisine, presence: true

  # once chef information is populated this search can be implemented
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :cuisine ],
    associated_against: {
      user: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/chef_review.rb
class ChefReview < ApplicationRecord
  belongs_to :booking
  belongs_to :chef
  validates :rating, inclusion: { in: [1,2,3,4,5], allow_nil: false }
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :recipe

  validates :description, presence: false
  validates :ingredient, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
  validates :content, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  has_many :bookings
  has_many :recipe_reviews, through: :bookings
  has_many :measurements, dependent: :destroy
  has_many :ingredients, through: :measurements
  has_one_attached :photo

  acts_as_taggable_on :tags
  acts_as_favoritable

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :cuisine, presence: true
  validates :cook_time, presence: true
  validates :photo, presence: true
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }

  monetize :price_cents


  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :cuisine, :name, :description ],
    using: {
      tsearch: { prefix: true }
    }

    # def unavailable_dates
    #   bookings.pluck(:date)
    # end

    # def unavailable_times
    #   bookings.pluck(:start_time, :end_time).map do |range|
    #     { from: range[0], to: range[1] }
    #   end
    # end
end

app/models/recipe_review.rb
class RecipeReview < ApplicationRecord
  belongs_to :booking
  belongs_to :recipe
  validates :rating, inclusion: { in: 1..5, allow_nil: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_favoritor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :bookings
  has_one_attached :photo
  has_one :chef
  has_many :chef_reviews, through: :bookings
  has_many :recipe_reviews, through: :bookings

  # after_create :send_welcome_email

  def owns?(item)
    item.user==self
  end


  private

  def send_welcome_email
    UserMailer.with(user: user).welcome_email.deliver.now
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, except: []
  before_action :set_recipe, only: [:show, :update, :edit, :destroy, :toggle_favorite]
  
  def top
    @recipes = Recipe.joins(:recipe_reviews).where(recipe_reviews:{rating: 5})
  end

  def toggle_favorite
    @recipe = Recipe.find_by(id: params[:id])
    current_user.favorited?(@recipe)  ? current_user.unfavorite(@recipe) : current_user.favorite(@recipe)
  end


  def index
    if params[ :query ].present?
      @recipes = policy_scope(Recipe).global_search(params[ :query ])
    elsif params[:tag].present?
      @recipes = policy_scope(Recipe).tagged_with(params[:tag])
    else
      @recipes = policy_scope(Recipe)
    end
  end

  def show
    # @recipes = Recipe.find(params[:id])
    # @related_recipes = @recipes.find_related_tags
    if user_signed_in? 
      @bookings_unsorted = current_user.bookings 
      @bookings = @bookings_unsorted.sort_by(&:id) 
      @next_booking = @bookings.last 
    end
    # raise
    # needed to add ingredient and measurements in recipe show page
    @measurement = Measurement.new
    # chef name to display link to chef
    @chef_name = "#{@recipe.chef.user.first_name + " " + @recipe.chef.user.last_name}"
  end

  def new
    @recipe = Recipe.new
    authorize @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)
    # creating chef instance to link recipe chef to new recipe by current user
    @recipe.chef = current_user.chef
    authorize @recipe

    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end

  end

  def edit
  end

  def update
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe.destroy
    redirect_to chef_dashboard_path(@recipe.chef)
  end

  private

  def set_recipe
     # recipes/:id
    @recipe = Recipe.find(params[:id])
    authorize @recipe
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :cuisine, :cook_time, :price, :photo, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chef_reviews_helper.rb
module ChefReviewsHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_like_button.html.erb
<%# <script src="https://use.fontawesome.com/releases/v5.8.1/js/all.js"></script> %>

<div class="like-icon mx-2<%= 'red' if current_user.favorited?(recipe) %>"data-id="<%= recipe.id %>">
  <i class="fas fa-heart" aria-hidden="true"></i>
</div>

app/views/recipes/_toggle_favorite.js.erb
var recipeId = '<%= @recipe.id %>'
function toggleLikeButton(recipeId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${recipeId}']`)
  likeButton.classList.toggle('red');
}
toggleLikeButton(recipeId);

app/views/recipes/_top.html.erb
<div class="container">
    <h2 class="heading-1 text-center">Top Recipes</h2>
</div>


<div class="my-4 d-flex overflow-x">
  <% recipes.each do | recipe | %>
     <%= link_to recipe_path(recipe) do  %>
      <div class="container">
        <div class="card-category card-home  effect1" style="background-image:url(<%=     cl_image_path recipe.photo.key%>)">
        </div>
        <div class=" card-body pb-0 text-center">
          <%= link_to recipe.name, recipe_path(recipe),class: "recipe-link" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

app/views/recipes/index.html.erb
<!-- Tagged list for quick access -->

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Refine Search
    <%= image_tag "filter.svg" %> </button>
  <div class="dropdown-menu", id="tag_container" aria-labelledby="dropdownMenuButton">
    <div class="container">
    <div class="d-flex flex-wrap tag-cloud my-6">
      <%# <li class="tag-cloud"> %>
          <%  Recipe.tag_counts_on(:tags).each do |tag| %>
            <small class="my-2"><%= link_to "#{tag.name} (#{tag.taggings_count})" , recipes_path(tag: tag.name)%></small>

          <% end %>
      </div>
    </div>
  </div>
</div>
<!-- End of Tagged list for quick access -->






<!-- list of recipes -->
<div class="recipe-cards my-4">
  <% @recipes.each do | recipe | %>
   <%= link_to recipe_path(recipe) do  %>
      <div class="container">
        <div class="recipe-index" id="recipe-card-style" style="background-image: url(<%= cl_image_path recipe.photo.key%>)">
        </div>
        <div class="recipe-info card-body pb-0 effect2">
          <div class="row justify-content-center">
            <%= link_to recipe.name, recipe_path(recipe),class: "recipe-link" %>
            <!-- like button -->
            <div class="container">
              <p class="tinytext text-center mt-2 mb-0">add to favourites</p>
              <div class="text-center" id="like-heart">
              <% if user_signed_in? %>
                <%= link_to toggle_favorite_recipe_path(recipe), remote: true, method: :post do %>
                  <p><%= render 'recipes/like_button', recipe: recipe %> </p>  <!--CAUSING ERRORS IN FOOTER STYLING-->
                <% end %>
              <% end %>
              </div>
            </div>
          <% end %>
      </div>






          <div class="row">
              <div class="col-6">
                <p><%= recipe.cuisine %></p>
                <p><i class="far fa-clock "></i> <%= recipe.cook_time %> mins</p>
              </div>
              <div class="col-6">
                <p><%= recipe.recipe_reviews.blank? ? "✩ 0 reviews" : "⭐️ " * recipe.recipe_reviews.average(:rating).round(2) %> </p>
                <p><%= humanized_money_with_symbol(recipe.price) %> / hr</p>
              </div>
            </div>
        </div>
      </div>
  <% end %>
</div>
<!--  -->

<div class="container text-center my-2 justify-content-between">
  <div class="d-flex justify-content-between row">
    <div class="mr-auto px-2">
      <%= link_to "All Chefs", chefs_path, class: "btn button shadow" %>
    </div>
    <div class="px-2">
      <%= link_to "⬆", recipes_path, class: "btn btn-light shadow" %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<!-- recipe review form and recipe image-->
<div class="container  p-4" id="add-measurement" style="width: 100%;">
  <div class="row card shadow-sm card-body justify-content-center">
    <div class="col-12 col-md-8 ">
     <div class="container recipe-svg text-center"><%= image_tag "recipe.svg"%></div>
     <br>
      <h1 class="text-center newrecipeh1">Add Recipe</h1>
      <br>

      <%= simple_form_for @recipe do |f| %>
        <%= f.input :name, label: "What is the name of your recipe?", class:"recipe_input_field"%>
        <%= f.input :description, id:"recipe_description", label: "Recipe details:" %>
        <%= f.input :cuisine, label: "What is the cuisine type?" %>
        <%= f.input :cook_time, label: "What is the cook time" %>
        <%= f.input :price, label: "What is the session cost per hour?" %>
        <%= f.input :photo, label: "Add a photo" %>
        <%= f.input :tag_list, label: "Add tags", hint: "Add your tags, separated by commas" %>
        <%= f.button :submit, class: "btn button col-12" %>
      <% end %>
    </div>
  </div>
</div>
<!--  -->

app/views/recipes/show.html.erb
<!-- recipe image -->
<div class="banner my-0" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(<%= cl_image_path @recipe.photo.key %>);">
</div>
<!--  -->

<!-- recipe heading -->
<div class="container head-container">
  <h1 class="text-center recipe-head"> <%= @recipe.name %> </h1>
</div>
<!--  -->

<!-- recipe details -->
<div class="container recipe-details pt-3">
  <h4 class="chef-recipe-header4"> Recipe Courtesy of</h4><%=  link_to @chef_name, chef_path(@recipe.chef), class: "d-flex justify-content-center chef-recipe-name" %>
  <p class="text-center "><%= @recipe.recipe_reviews.blank? ? "" : "⭐️ " * @recipe.recipe_reviews.average(:rating).round(2) %></p>
  <div class="container card p-4 shadow" >
    <div class="container px-3">
      <p class="recipe-head"><i class="far fa-clock mt-3"></i> <strong>Cook time:</strong> <%= @recipe.cook_time %> mins</p>
      <p><%= @recipe.description %></p>
    </div>
  <!-- price -->
    <h2 class="text-center recipe-head pb-0">Chef Session </h2>
    <p id="cost-recipe" class="text-center my-0 recipe-head"> <%= humanized_money_with_symbol(@recipe.price) %> / hour</p>
  <!--  -->
  <!-- Booking Link -->
    <% if user_signed_in?  && current_user != @recipe.chef.user || @bookings.nil?%>
      <div class="container text-center mt-3 mb-4">
        <label><em>Ready to start cooking with chef <%= @chef_name %>?</em></label>
      <%= link_to "Book Session", new_recipe_booking_path(@recipe), class: "btn button button-book col-8 mt-3", id:"chef-btn" %>
      </div>
    <% end %>
  </div>
  <!--  -->
<br>
  <!-- ingredients/ SHOPPING LIST -->
  <% if user_signed_in?  && current_user ==  @recipe.chef.user %>
    <div class="container card pt-3 shadow-sm shopping-list-container" id="shopping-list" >
      <h4 class="text-center recipe-link mb-0">Shopping List</h4>
      <p class="text-center recipe-link mb-0">for Chef <%= @chef_name %>'s </p>
      <p class="text-center mt-0 chef-recipe-name"> <%= @recipe.name %> </p>
      <hr class="mt-0">
      <p class="text-center mb-3"><em>Lets get cooking!</em></p>
      <p class="text-center"><i class="fas fa-shopping-cart"></i> </p>
      <div class="container px-0 pb-3">
        <% @recipe.measurements.each do |measurement| %>
          <div class="shopping-list-ingredients">
            <div class="row">
              <div class="col-2">
                <span  id="measurement-<%= measurement.id %>" class="shopping-list-checkbox">
                  <% if user_signed_in?  && current_user ==  measurement.recipe.chef.user %>
                    <%= link_to "X", measurement_path(measurement), remote: true, method: :delete,  class:"recipe-link" %>
                  <% else %>
                    <i class="far fa-square"></i>
                  <% end %>
                </span>
              </div>
              <div class="col-10 shopping-list-description">
                <span>
                  <%= measurement.description %> <%= measurement.ingredient.capitalize %>
                </span>

            </div>
          </div>
        <% end %>
        <p class="text-center"><%= link_to "Save List", bookings_path, class: "btn button mt-4 shadow", id:"chef-btn" %></p>
      </div>
    </div>
    <% elsif user_signed_in? && @next_booking.recipe.present? && @next_booking.recipe == @recipe && @next_booking.recipe_review.nil? && @next_booking.chef_review.nil? %>
     <div class="container card pt-3 shadow-sm shopping-list-container" id="shopping-list" >
      <h4 class="text-center recipe-link mb-0">Shopping List</h4>
      <p class="text-center recipe-link mb-0">for Chef <%= @chef_name %>'s </p>
      <p class="text-center mt-0 chef-recipe-name"> <%= @recipe.name %> </p>
      <hr class="mt-0">
      <p class="text-center mb-3"><em>Lets get cooking!</em></p>
      <p class="text-center"><i class="fas fa-shopping-cart"></i> </p>
      <div class="container px-0 pb-3">
        <% @recipe.measurements.each do |measurement| %>
          <div class="shopping-list-ingredients">
            <div class="row">
              <div class="col-2">
                <span  id="measurement-<%= measurement.id %>" class="shopping-list-checkbox">
                  <% if user_signed_in? && current_user ==  measurement.recipe.chef.user %>
                    <%= link_to "X", measurement_path(measurement), remote: true, method: :delete,  class:"recipe-link" %>
                  <% else %>
                    <i class="far fa-square"></i>
                  <% end %>
                </span>
              </div>
              <div class="col-10 shopping-list-description">
                <span>
                  <%= measurement.description %> <%= measurement.ingredient.capitalize %>
                </span>
              </div>
            </div>
          </div>
        <% end %>
        <p class="text-center"><%= link_to "Save List", bookings_path, class: "btn button mt-4 shadow", id:"chef-btn" %></p>
      </div>
    </div>
  <% end %>
  <!--     -->

  <!-- ADD INGREDIENTS -->
  <% if user_signed_in?  && current_user == @recipe.chef.user %>
    <div class="container mt-5 mb-3 py-3 border shadow-sm text-center" id="add-measurement">
      <p class="text-center py-2 mb-1 text-dark"> Enter an Ingredient
      <%= simple_form_for([@recipe, @measurement], remote: true) do |f| %>
        <p class="mb-0"></i>Quantity / Measurement</p>
        <%= f.input_field :description, placeholder: "    1 oz" %>
        <p class="mb-0 mt-3"></i>Ingredient</p>
        <%= f.input_field :ingredient, placeholder: "    Chicken"%>
        <%= f.button :submit, "+ Add Ingredient", class: "btn button col-6 mt-3 shadow-sm" %>
      <% end %>
    </div>
  <% end %>
</div>
  <!--  -->

<% if  !@recipe.recipe_reviews.empty? %>
  <!-- RECIPE reviews -->
    <% @recipe.recipe_reviews.each do |review| %>
      <div class="notification mb-0 bg-white">
        <div class="mx-1">
          <%= cl_image_tag review.booking.user.photo.key, class: "avatar-large" %>
        </div>
        <div class="notification-content">
          <p class="my-0"><strong><%= review.booking.user.first_name %> <%= review.booking.user.last_name %></strong></p>
          <p><span><%= review.created_at.strftime("%B %e, %Y") %> |</span>  <%= "⭐️" * review.rating %></p>
          <p><%= review.content %></p>
        </div>
      </div>
    <% end %>
<% end %>

<!-- bottom links -->
<div class="container text-center my-2 justify-content-between">
  <div class="d-flex justify-content-between row">
    <div class="mr-auto px-2">
      <%= link_to "All Recipes", recipes_path, class: "btn btn-light shadow"%>
    </div>
    <div class="px-2">
      <%= link_to "⬆", recipe_path(@recipe), class: "btn btn-light shadow" %>
    </div>
  </div>
</div>

app/views/recipes/toggle_favorite.js.erb
var recipeId = '<%= @recipe.id %>'
function toggleLikeButton(recipeId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${recipeId}']`)
  likeButton.classList.toggle('red');
}
toggleLikeButton(recipeId);

app/views/recipes/top.html.erb
    <%= render 'recipes/top' %>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>