config/routes.rb
Rails.application.routes.draw do
  get 'booking_confirmation/show'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users
  root to: 'pages#home'
  get '/tagged', to: "recipes#tagged", as: :tagged
  get 'chef_dashboard', to: 'dashboards#chef_dashboard', as: :chef_dashboard
  get 'user_dashboard', to: 'dashboards#user_dashboard', as: :user_dashboard

  # /bookings -- /bookings/:id -- /bookings/:id/edit
  resources :bookings, only: [ :index, :show, :destroy, :edit, :update] do
    # /bookings/:id/chef_reviews/new
    resources :chef_reviews, only: [:new, :create]
    # /bookings/:id/recipe_reviews/new
    resources :recipe_reviews, only: [:new, :create]
  end

 # All CRUD actions for recipes
  resources :recipes do
    member do 
      post 'toggle_favorite', to: "recipes#toggle_favorite"
    end
    collection do
      get :top
    end
    # /recipes/:id/bookings/new
    resources :bookings, only: [:new, :create]

    # recipes/:id/measurements/:id
    resources :measurements, only: [:new, :create]
  end

  # /chats  -- /chats/:id
  resources :chats, only: [:index, :show] do
    # chats/:id/messages
    resources :messages, only: [:create, :destroy]
  end

  # /chefs/:id -- /chefs/new  -- /chefs
  resources :chefs, only: [:show, :new, :create, :index, :destroy]
  resources :measurements, only: [:destroy]

  # checkout
  resources :bookings, only: [] do
    resources :checkout_sessions, only: [:new]
    resources :booking_confirmations, only: [:new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  has_one :chat
  has_one :chef_review, dependent: :destroy
  has_one :recipe_review, dependent: :destroy

  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_after_start_time

  private

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, "must be after the start time")
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :booking
  has_many :messages
end

app/models/chef.rb
class Chef < ApplicationRecord
  belongs_to :user
  has_many :recipes, dependent: :destroy
  has_many :bookings, through: :recipes
  has_many :chef_reviews, through: :bookings

  validates :cuisine, presence: true

  # once chef information is populated this search can be implemented
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :cuisine ],
    associated_against: {
      user: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/chef_review.rb
class ChefReview < ApplicationRecord
  belongs_to :booking
  belongs_to :chef
  validates :rating, inclusion: { in: [1,2,3,4,5], allow_nil: false }
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :recipe

  validates :description, presence: false
  validates :ingredient, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
  validates :content, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  has_many :bookings
  has_many :recipe_reviews, through: :bookings
  has_many :measurements, dependent: :destroy
  has_many :ingredients, through: :measurements
  has_one_attached :photo

  acts_as_taggable_on :tags
  acts_as_favoritable

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :cuisine, presence: true
  validates :cook_time, presence: true
  validates :photo, presence: true
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }

  monetize :price_cents


  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :cuisine, :name, :description ],
    using: {
      tsearch: { prefix: true }
    }

    # def unavailable_dates
    #   bookings.pluck(:date)
    # end

    # def unavailable_times
    #   bookings.pluck(:start_time, :end_time).map do |range|
    #     { from: range[0], to: range[1] }
    #   end
    # end
end

app/models/recipe_review.rb
class RecipeReview < ApplicationRecord
  belongs_to :booking
  belongs_to :recipe
  validates :rating, inclusion: { in: 1..5, allow_nil: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_favoritor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :bookings
  has_one_attached :photo
  has_one :chef
  has_many :chef_reviews, through: :bookings
  has_many :recipe_reviews, through: :bookings

  # after_create :send_welcome_email

  def owns?(item)
    item.user==self
  end


  private

  def send_welcome_email
    UserMailer.with(user: user).welcome_email.deliver.now
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def chef_dashboard
    @chef = current_user.chef
    @bookings = @chef.bookings
    @recipes = @chef.recipes

    skip_authorization
  end

  def user_dashboard
    @user = current_user
    @bookings = @user.bookings
    @favorite_recipes = current_user.favorited_by_type('Recipe')
    skip_authorization
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chef_reviews_helper.rb
module ChefReviewsHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/dashboards/chef_dashboard.html.erb
<div class="container card shadow-sm p-4" id="add-measurement" >
<div class="container chef-svg text-center"><%= image_tag "chef.svg"%></div>
<h1 class="chef-dash-header text-center">Chef Dashboard</h1>

  <div class="container text-center card py-3 shadow-sm container-dash">
    <div class="row">
      <div class="col-12">
        <%= cl_image_tag current_user.photo.key, width: 175, height: 175,  crop: :fill, class: "chef-avatar mb-4"  %>
       </div>
       <div class="col-12">
        <h2 class="text-center mb-0">Chef</h2>
        <h2 class="user-dash-name" ><%= @chef.user.first_name%> <%= @chef.user.last_name %></h2>
      </div>
    </div>
  </div>

<!-- booking confirmation -->
<div class="container">
  <div class="row booking-confirm mt-4 text-center">
    <div class="col-12 card card-body pb-2 pt-3 shadow-sm">
        <% if @bookings.empty? %>
          <h3>You have no bookings</h3>
        <% else  %>
          <h4 class="chef-dash-header mt-2">Session Confirmation</h4>
          <h5 class="recipe-link"><%= @bookings[-1].recipe.name %></h5>
          <p class="recipe-link">with <%= @bookings[-1].user.first_name %> <%= @bookings[-1].user.last_name %></p>
          <p class="booking-times mb-0"><%= @bookings[-1].date.strftime("%B %e, %Y") %> </p>
          <p class="booking-times"><%= @bookings[-1].start_time.strftime("%I:%M%p") %> - <%= @bookings[-1].end_time.strftime("%I:%M%p") %></p>
          <div class="row text-center mx-4 mt-2">
            <div class="col-6">
              <p class="btn button px-3  shadow-sm" >Accept <i class="far fa-check-square"></i></p>
            </div>
            <div class="col-6">
              <p class="btn button px-3 shadow-sm">Decline <i class="fas fa-ban"></i></p>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

<!-- collapse menu -->

  <div id="accordion" class="my-4 shadow-sm">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0 text-center">
        <button class="text-decoration-none btn btn-link link-user-dash" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          My Recipes
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
         <!-- My Recipes -->
        <div class="container mt-4">
          <div class="container">
            <h2 class="text-center mb-4">My Recipes</h2>
            <div class="container text-center" >
              <%= link_to "Add Recipe", new_recipe_path, class: "btn btn-light shadow-sm mb-4 d-flex justify-content-center", id:"chef-btn" %>
            </div>
            <% if !@recipes.empty? %>
              <% @recipes.each do |recipe| %>
                <div class="container mt-3">
                  <div class="row">
                    <div class="col-3">
                      <%= link_to cl_image_tag recipe.photo.key, class: "avatar-large",  crop: :fill %>
                    </div>
                    <div class="col-9">
                     <div class="row justify-content-center">
                       <h5 class="col-8 pl-2 pr-0"><%= link_to recipe.name, recipe_path(recipe),class: "link-recipe-dash text-decoration-none font-weight-bold" %></h5>
                     <p class="col-1 pl-1 mt-0"><%= link_to "X", recipe_path(recipe), class:"text-secondary text-decoration-none font-weight-bold", method: :delete, data: {confirm: "Are you sure?" } %><p>
                     </div>

                    </div>
                  </div>
              </div>
              <hr>
              <% end %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
    <!-- Customer reviews -->
    <div class="card">
      <div class="card-header" id="headingTwo">
        <h5 class="mb-0 text-center">
          <button class="text-decoration-none link-user-dash btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Customer Reviews
          </button>
        </h5>
      </div>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body">
          <% if !@bookings.empty? %>
            <% @bookings.each do |booking|
            %>
              <% if !booking.chef_review.nil? %>
              <div class="container mt-3">
                <div class="row">
                  <div class="col-3">
                    <%= link_to cl_image_tag booking.user.photo.key, class: "avatar-large",  crop: :fill %>
                  </div>
                  <div class="col-9">
                    <h5 class="mb-0 p-1"><%="#{booking.user.first_name} #{booking.user.last_name} " %></h5 >
                    <p class="p-1 mb-0"><strong>Rating:</strong> <%= booking.chef_review.rating %> </p>
                    <p class="p-1 mt-0"><strong>Content:</strong> <%= booking.chef_review.content %></p>
                  </div>
                </div>
              </div>
              <hr>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <!-- recipe reviews -->
    <div class="card">
      <div class="card-header" id="headingThree">
        <h5 class="mb-0 text-center">
          <button class="text-decoration-none link-user-dash btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            Customer Recipe Reviews
          </button>
        </h5>
      </div>
      <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
        <div class="card-body">
           <% if !@bookings.empty? %>
            <% @bookings.each do |booking|
            %>
              <% if !booking.recipe_review.nil? %>
              <div class="container mt-3">
                <div class="row">
                  <div class="col-3">
                    <%= link_to cl_image_tag booking.user.photo.key, class: "avatar-large",  crop: :fill %>
                  </div>
                  <div class="col-9">
                    <h5 class="mb-0 p-1"><%="#{booking.user.first_name} #{booking.user.last_name} " %></h5 >
                    <p class="p-1 mb-0"><strong>Rating:</strong> <%= booking.recipe_review.rating %> </p>
                    <p class="p-1 mt-0"><strong>Content:</strong> <%= booking.recipe_review.content %></p>
                  </div>
                </div>
              </div>
              <hr>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<!-- account cancellation -->
  <div class="container text-center mb-4">
    <p><%= link_to "Delete Chef Account",  chef_path(@chef), method: :delete, data: {confirm: "Are you sure?" }, class: "text-decoration-none mt-4 btn btn-light mb-4 del-chef" %></p>
  </div>
</div>

app/views/dashboards/user_dashboard.html.erb
<div class="container card shadow-sm p-4" id="add-measurement">
<div class="container chef-svg text-center"><%= image_tag "user.svg"%></div>
  <h1 class="chef-dash-header text-center">User dashboard</h1>
  <div class="container text-center card py-3 shadow-sm  container-dash">
    <div class="row">
      <div class="col-12 ">
        <%= cl_image_tag current_user.photo.key, width: 175, height: 175,  crop: :fill, class: "chef-avatar mb-4"  %>
       </div>
       <div class="col-12">
        <h2 class="user-dash-name" ><%= current_user.first_name %> <%= current_user.last_name %></h2>
          <!-- create chef link -->
        <% unless current_user.chef.present? %>
          <%= link_to "Become a chef", new_chef_path, class: "btn btn-light mt-2 shadow-sm", id: "chef-btn" %>
        <% end %>
      </div>
    </div>
  </div>

<!-- booking confirmation -->
  <div class="container">
    <div class="row booking-confirm mt-4 text-center">
      <div class="col-12 card card-body pb-2 pt-3 container-dash shadow-sm">
        <h5>Next Session</h5>
        <% if @bookings.empty? || !@bookings[-1].chef_review.blank? ||  !@bookings[-1].recipe_review.blank? %>
          <h4 class="chef-dash-header mt-2">Book your next session </h4>
          <p><i class="far fa-hand-point-right"></i><%= link_to "Recipes", recipes_path, class:"text-uppercase link-recipe-dash font-weight-bold text-decoration-none" %></p>
        <% else %>
          <h2 class="recipe-link"><%= @bookings[-1].recipe.name %></h2>
          <p></p>
          <p class="booking-times"><%= @bookings[-1].date.strftime("%B %e, %Y") %> <br> <%= @bookings[-1].start_time.strftime("%I:%M%p") %> - <%= @bookings[-1].end_time.strftime("%I:%M%p") %></p>
        <% end %>
      </div>
    </div>
  </div>

<!-- collapse menu -->
  <div id="accordion" class="mt-4 shadow-sm">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0 text-center">
          <button class="text-decoration-none btn btn-link link-user-dash" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Booking History
          </button>
        </h5>
      </div>

      <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body">
         <!-- booking history -->
         <% if !@bookings.empty? %>
          <% @bookings.each do |booking| %>
          <div class="container mt-3">
            <div class="row">
              <div class="col-3">
                <%= link_to cl_image_tag booking.recipe.photo.key, class: "avatar-large",  crop: :fill %>
              </div>
              <div class="col-9">
                <p class="mb-0"><%= link_to "Booking # #{booking.id}", booking_path(booking),class: "link-recipe-dash text-decoration-none font-weight-bold" %></p>
                <p class="mb-0 pl-1"> Chef <%= booking.recipe.chef.user.first_name %> <%= booking.recipe.chef.user.last_name %></p>
                <p class="mt-0 pl-1"><%= booking.recipe.name %></p>
             </div>
            </div>
           </div>
           <hr>
          <% end %>
         <% end %>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-header" id="headingTwo">
        <h5 class="mb-0 text-center">
          <button class="text-decoration-none btn btn-link link-user-dash collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            My Chef Reviews
          </button>
        </h5>
      </div>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body">
          <% if !current_user.chef_reviews.empty? %>
            <% current_user.chef_reviews.each do |chef_review|
            %>
            <div class="container mt-3">
              <div class="row">
                <div class="col-3">
                  <%= link_to cl_image_tag chef_review.chef.user.photo.key, class: "avatar-large",  crop: :fill %>
                </div>
                <div class="col-9">
                  <h5 class="mb-0"><%= link_to "Chef  #{chef_review.chef.user.first_name} #{chef_review.chef.user.last_name} ", chef_path(chef_review.chef),class: "link-recipe-dash text-decoration-none font-weight-bold" %></h5 >
                   <p class="p-1 mb-0"><strong>Rating:</strong> <%= chef_review.rating %> </p>
                  <p class="p-1 mt-0"><strong>Content:</strong> <%= chef_review.content %></p>
                </div>
              </div>
            </div>
            <hr>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingThree">
        <h5 class="mb-0 text-center">
          <button class=" text-decoration-none btn btn-link link-user-dash collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            My Recipe Reviews
          </button>
        </h5>
      </div>
      <div id="collapseThree" class="collapse " aria-labelledby="headingThree" data-parent="#accordion">
        <div class="card-body">
          <% if !current_user.recipe_reviews.empty? %>
            <% current_user.recipe_reviews.each do |recipe_review|
            %>
            <div class="container mt-3">
              <div class="row">
                <div class="col-3">
                  <%= link_to cl_image_tag recipe_review.recipe.photo.key, class: "avatar-large",  crop: :fill %>
                </div>
                <div class="col-9">
                  <h5 class="mb-0"><%= link_to recipe_review.recipe.name, recipe_path(recipe_review.recipe),class: "link-recipe-dash text-decoration-none font-weight-bold" %></h5 >
                  <p class="pl-1 mb-0"><strong>Rating:</strong> <%= recipe_review.rating %> </p>
                  <p class="pl-1 mt-0"><strong>Content:</strong> <%= recipe_review.content %></p>
                </div>
              </div>
            </div>
            <hr>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
      <div class="card mb-4">
        <div class="card-header" id="headingFour">
          <h5 class="mb-0 text-center">
            <button class="text-decoration-none btn btn-link link-user-dash collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
              Favourite Recipes
            </button>
          </h5>
        </div>
        <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
          <div class="card-body">
            <% if !@favorite_recipes.empty? %>
              <% @favorite_recipes.each do |recipe| %>
              <div class="container mt-3">
                <div class="row">
                  <div class="col-3">
                    <%= link_to cl_image_tag recipe.photo.key, class: "avatar-large",  crop: :fill %>
                  </div>
                  <div class="col-9">
                   <%= link_to recipe.name, recipe_path(recipe),class: "pl-0 link-recipe-dash text-decoration-none font-weight-bold" %>
                  </div>
                </div>
              </div>
              <hr>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>