config/routes.rb
Rails.application.routes.draw do
  get 'booking_confirmation/show'
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users
  root to: 'pages#home'
  get '/tagged', to: "recipes#tagged", as: :tagged
  get 'chef_dashboard', to: 'dashboards#chef_dashboard', as: :chef_dashboard
  get 'user_dashboard', to: 'dashboards#user_dashboard', as: :user_dashboard

  # /bookings -- /bookings/:id -- /bookings/:id/edit
  resources :bookings, only: [ :index, :show, :destroy, :edit, :update] do
    # /bookings/:id/chef_reviews/new
    resources :chef_reviews, only: [:new, :create]
    # /bookings/:id/recipe_reviews/new
    resources :recipe_reviews, only: [:new, :create]
  end

 # All CRUD actions for recipes
  resources :recipes do
    member do 
      post 'toggle_favorite', to: "recipes#toggle_favorite"
    end
    collection do
      get :top
    end
    # /recipes/:id/bookings/new
    resources :bookings, only: [:new, :create]

    # recipes/:id/measurements/:id
    resources :measurements, only: [:new, :create]
  end

  # /chats  -- /chats/:id
  resources :chats, only: [:index, :show] do
    # chats/:id/messages
    resources :messages, only: [:create, :destroy]
  end

  # /chefs/:id -- /chefs/new  -- /chefs
  resources :chefs, only: [:show, :new, :create, :index, :destroy]
  resources :measurements, only: [:destroy]

  # checkout
  resources :bookings, only: [] do
    resources :checkout_sessions, only: [:new]
    resources :booking_confirmations, only: [:new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  has_one :chat
  has_one :chef_review, dependent: :destroy
  has_one :recipe_review, dependent: :destroy

  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_after_start_time

  private

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, "must be after the start time")
    end
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :booking
  has_many :messages
end

app/models/chef.rb
class Chef < ApplicationRecord
  belongs_to :user
  has_many :recipes, dependent: :destroy
  has_many :bookings, through: :recipes
  has_many :chef_reviews, through: :bookings

  validates :cuisine, presence: true

  # once chef information is populated this search can be implemented
  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :cuisine ],
    associated_against: {
      user: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/chef_review.rb
class ChefReview < ApplicationRecord
  belongs_to :booking
  belongs_to :chef
  validates :rating, inclusion: { in: [1,2,3,4,5], allow_nil: false }
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :recipe

  validates :description, presence: false
  validates :ingredient, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
  validates :content, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  has_many :bookings
  has_many :recipe_reviews, through: :bookings
  has_many :measurements, dependent: :destroy
  has_many :ingredients, through: :measurements
  has_one_attached :photo

  acts_as_taggable_on :tags
  acts_as_favoritable

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :cuisine, presence: true
  validates :cook_time, presence: true
  validates :photo, presence: true
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }

  monetize :price_cents


  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :cuisine, :name, :description ],
    using: {
      tsearch: { prefix: true }
    }

    # def unavailable_dates
    #   bookings.pluck(:date)
    # end

    # def unavailable_times
    #   bookings.pluck(:start_time, :end_time).map do |range|
    #     { from: range[0], to: range[1] }
    #   end
    # end
end

app/models/recipe_review.rb
class RecipeReview < ApplicationRecord
  belongs_to :booking
  belongs_to :recipe
  validates :rating, inclusion: { in: 1..5, allow_nil: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_favoritor
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :bookings
  has_one_attached :photo
  has_one :chef
  has_many :chef_reviews, through: :bookings
  has_many :recipe_reviews, through: :bookings

  # after_create :send_welcome_email

  def owns?(item)
    item.user==self
  end


  private

  def send_welcome_email
    UserMailer.with(user: user).welcome_email.deliver.now
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 text-white-50">
    <div class="container text-center">

     <div class="footer text-center navbar-fixed-bottom">
    <div class="footer-links">
    <a href="https://github.com/cdrmr18/kook-app"><i class="fab fa-github mr-4 mb-4 pt-4"></i></a>
     <a href="https://www.instagram.com/lewagonmelbourne"><i class="fab fa-instagram mr-4 mb-4 pt-4"></i></a>
      <a href="https://twitter.com/LeWagonMEL"><i class="fab fa-twitter mr-4 mb-4 pt-4"></i></a>
      <div class="footer-copyright">
      <small><p class="col-xs-1 text-center">Powered by <i class="fas fa-heart"></i> from the Kook Team</p></small>
    </div>
  </div>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <%= link_to "/", class: "navbar-brand" do %>
          <%= image_tag "LOGO.svg" %>
        <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon "> </span></span>
          <% if user_signed_in? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
        </button>




    <!-- search bar -->
     <% if controller.controller_name == 'chefs' && controller.action_name == 'index'%>
          <div class="container-fluid">
            <a class="navbar-brand"></a>
              <%= form_tag chefs_path, method: :get do %>
              <div class="d-flex">
                <%= text_field_tag :query, params[:query], class: "form-control me-2", id: "form-cont",
                    placeholder: "cuisine or chef" %>
                    <%= submit_tag "search", class:"btn",  id: "search-btn" %>
              </div>
            <% end %>
          </div>
     <% elsif controller.controller_name == 'recipes' && controller.action_name == 'index' %>
        <div class="container-fluid">
            <a class="navbar-brand"></a>
              <%= form_tag recipes_path, method: :get do %>
              <div class="d-flex">
                <%= text_field_tag :query, params[:query], class: "form-control me-2", id: "form-cont",
                    placeholder: "cuisine or recipe" %>
                    <%= submit_tag "search", class:"btn",  id: "search-btn" %>
              </div>
            <% end %>
          </div>
     <% end %>
    <!-- search bar end -->

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto navbar-fixed-top">
          <%# if user_signed_in? %>
            <li class="nav-item dropdown">
              <% if user_signed_in? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag ("https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="col-md-12">
                <div div class="dropdown-menu dropdown-menu-right" id="drpdown" aria-labelledby="navbarDropdown">
                    <div class="inblk"><%= link_to "Recipes", recipes_path, class: "dropdown-item text_dropdown" %></div>
                    <div class="inblk"><%= link_to "Chefs", chefs_path, class: "dropdown-item text_dropdown" %></div>
                    <div class="inblk"><%= link_to "Bookings", bookings_path, class: "dropdown-item text_dropdown" %></div>
                    <div class="inblk"><%= link_to "Dashboard", user_dashboard_path, class: "dropdown-item text_dropdown" %></div>
                    <% if user_signed_in? && current_user.chef.present? %>
                      <div class="inblk"><%= link_to "Chef Dashboard", chef_dashboard_path, class: "dropdown-item text_dropdown" %></div>
                    <% end %>
                    <div class="inblk"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item text_dropdown" %></div>
                  </div>
                </div>
              </div>
            </li>
           <%# else %>
              
                <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
               
            <%# end %>
         </ul>
       </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">

    <%= render 'layouts/navigation' %>


    <!-- DEVISE ALERTS -->
      <p class="notice my-0"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <!-- DEVISE ALERTS END -->

    <main>
      <div>
        <%= yield %>
      </div>
    </main>

        <!-- STICKER FOOTER -->

    <div id="page-content">



    </div>



  
      <%= render 'layouts/footer' %>
  
    <!--STICKY FOOTER END DIV -->

  </body>
</html>